class E {
    public static void main(String[] args) {
        // some code ...
        
        try {
            // some code ...
        } catch(Exception e) {
            // some code ...
        }finally{

        }

        // some code ...
        // some code ...
        // some code ...
        // some code ...

        try {
            // some code ...
        } catch(Exception e) {
            // some code ...
        }
        finally{
            
        }
        
        // some code ...
        // some code ...
        // some code ...
        // some code ...

        try {
            // some code ...
        } catch(Exception e) {
            // some code ...
        }


    }    
}